### ISSUE TITLE
version 1.35.0 get FATAL:kernel too old in openvz 

### ISSUE THREAD

**Issue by mengyyy** [clamsawd/aria2-static-builds#12]
I try install for this static build (1.35.0) but when i run aria2c i got  this error.
And get the same error by installing with .deb file.

**FATAL: kernel too old
Aborted** 

But after i build from the source code, i could run the version 1.35.0.

My server is _Ubuntu 16.04.6 LTS (GNU/Linux 2.6.32-48-pve x86_64)_
I build 1.35.0 from source code by this link

https://setsuna.moe/2018/10/27/ubuntu-16-04%E7%BC%96%E8%AF%91aria2/

**Comment by dmesg00** [comment]
@mengyyy You must upgrade to kernel 3.2.x or higher

`$ file /usr/bin/aria2c`

`/usr/bin/aria2c: ELF 64-bit LSB executable, x86-64, version 1 (GNU/Linux), statically linked, for GNU/Linux 3.2.0, BuildID[sha1]=ad72505202e67f313ff7bc9376d86ff00978fcd5, stripped`

The kernel 3.2.x exists since 2012 (**7 years ago**) and Ubuntu 16.04 came with a higher version (**kernel 4.4**). Ubuntu 12.04 came with kernel 3.2.0

**Comment by mengyyy** [comment]
Openvz could not be upgraded easily.

**Comment by dmesg00** [comment]
@mengyyy I currently use GCC 8.3.0 that compiles for kernel 3.2.0 as a minimum.

Previously I used the GCC 6.3.0 compiler that I compiled for 2.6.32 or higher kernels. The last version that was compiled with this version of GCC was the previous one (1.34.0).

https://github.com/q3aql/aria2-static-builds/releases/tag/v1.34.0
