### ISSUE TITLE
request: amd64 builds

### ISSUE THREAD

**Issue by elig0n** [clamsawd/aria2-static-builds#15]
can you please add builds for that platform ?

**Comment by dmesg00** [comment]
I don't understand your request. The builds for this platform are already available. I only build for i386 (x86), amd64 (x86_64) and arm32.

**Comment by elig0n** [comment]
I mean for a platform that has this architecture :

    $ uname -m 
     amd64

and not

    $ uname -m 
     x86_64

**Comment by dmesg00** [comment]
x64, x86_64 and amd64 are the same. Different distributions and S.O use one or another way of naming the same architecture. By default, the x86_64 architecture is compiled using the amd64 instructions because they (AMD) was the first to implement it. There are also some exceptions where it is compiled for intel-64 (which of course is compatible with AMD, but is more optimized for Intel).
