### ISSUE TITLE
macOS build ?

### ISSUE THREAD

**Issue by chromer030** [clamsawd/aria2-static-builds#22]

**Comment by dmesg00** [comment]
To compile a MacOS version I would need to buy a computer from Apple (which I'm not going to do).

From Linux it is easy to cross-compile to Windows and that's why I upload such builds. On the other hand, you can't do the same with MacOS, cross-compiling is impossible or very complicated because you need the SDK or Xcode.

I recommend that you use the versions that are uploaded on the official site or that you install a manage package system such as MacPorts or Homebrew. Both have the latest version of the package.

[https://ports.macports.org/port/aria2/](https://ports.macports.org/port/aria2/)
[https://formulae.brew.sh/formula/aria2](https://formulae.brew.sh/formula/aria2)
